name: sparse-ho-env

dependencies:
    - ipython
    - numpy>=1.12
    - scipy>=0.18.0
    - scikit-learn>=0.21
    - numba
    - seaborn>=0.7
    - matplotlib>=2.0.0
    - pip
    - cvxpy
    - torch==1.3.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - cvxpylayers

    - pip:
        - download
        - hyperopt
