name: sparse-ho-env

dependencies:
    - ipython
    - numpy>=1.12
    - scipy>=0.18.0
    - scikit-learn>=0.21
    - numba
    - seaborn>=0.7
    - matplotlib>=2.0.0
    - pip

    - pip:
        - download
        - hyperopt
        - cvxpy
        - torch==1.7.1+cpu
        - torchvision==0.8.2+cpu
        - torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
        - cvxpylayers
